(function(g){var window=this;var LEa=function(a,b){return g.Qb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Dn(a.A,b,c)},MEa=function(a,b){var c=[];
g.Ek(b,function(d){try{var e=g.Co.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Bo(e)&&c.push(d)},a);
return c},NEa=function(a,b){var c=MEa(a,b);
g.z(c,function(d){g.Co.prototype.remove.call(this,d)},a)},OEa=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},PEa=function(a,b){g.nb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},QEa=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},d6=function(){},REa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},SEa=function(a){if(a.Xd&&"function"==typeof a.Xd)return a.Xd();
if("string"===typeof a)return a.split("");if(g.Ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Mb(a)},TEa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ra(a)||"string"===typeof a)g.z(a,b,void 0);else{if(a.kf&&"function"==typeof a.kf)var c=a.kf();else if(a.Xd&&"function"==typeof a.Xd)c=void 0;else if(g.Ra(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Nb(a);d=SEa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},UEa=function(a,b,c,d){var e=new g.rn(null,void 0);
a&&g.sn(e,a);b&&g.tn(e,b);c&&g.un(e,c);d&&(e.u=d);return e},e6=function(a,b){g.ip[a]=!0;
var c=g.gp();c&&c.publish.apply(c,arguments);g.ip[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.on;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",VEa(this,a.capabilities||""),WEa(this,a.experiments||""))},VEa=function(a,b){a.capabilities.clear();
g.Ie(b.split(","),g.Xa(LEa,XEa)).forEach(function(c){a.capabilities.add(c)})},WEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},YEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},ZEa=function(a){return new g6(a)},$Ea=function(a){return Array.isArray(a)?g.Oc(a,ZEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Oc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},aFa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.jb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.jb(a,function(c){return h6(c,b)})},bFa=function(){var a=(0,g.wt)();
a&&NEa(a,a.o.Uh(!0))},n6=function(){var a=g.At("yt-remote-connected-devices")||[];
g.Cb(a);return a},cFa=function(a){if(g.ob(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},dFa=function(a){g.zt("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.At("yt-remote-device-id");a||(a=k6(),g.zt("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.nb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.nb(a,b);g.Ct()&&g.Eb(a,b);a=cFa(a);if(g.ob(a))try{g.Vq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Wq("remote_sid",a.join(","),-1)}catch(c){}},eFa=function(){return g.At("yt-remote-session-browser-channel")},fFa=function(){return g.At("yt-remote-local-screens")||[]},gFa=function(){g.zt("yt-remote-lounge-token-expiration",!0,86400)},hFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(fFa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.Qi(c,function(d){return!g.nb(b,d)})&&gFa();
g.zt("yt-remote-local-screens",a,31536E3)},iFa=function(a,b){g.zt("yt-remote-session-browser-channel",a);
g.zt("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.nb(c,d)||c.push(d);dFa(c);q6()},r6=function(a){a||(g.Bt("yt-remote-session-screen-id"),g.Bt("yt-remote-session-video-id"));
q6();a=n6();g.rb(a,p6());dFa(a)},jFa=function(){if(!s6){var a=g.Io();
a&&(s6=new g.to(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},kFa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},lFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?mFa(a.shift(),function(){t6(a)}):u6()},nFa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},mFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=lFa();
a&&a(!1,"No cast extension found")},pFa=function(){if(oFa){var a=2,b=lFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;mFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},qFa=function(){pFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Jd=b;this.C=(0,g.x)(this.xG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.Jd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.ig(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Jd);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return REa(a)},z6=function(){},A6=function(){},rFa=function(){},tFa=function(a){return(a=sFa(a))?new ActiveXObject(a):new XMLHttpRequest},sFa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.w1(this);this.u=new g.hg;this.u.setInterval(250)},vFa=function(a,b,c){a.Yl=1;
a.Xh=a6(b.clone());a.jk=c;a.F=!0;uFa(a,null)},C6=function(a,b,c,d,e){a.Yl=1;
a.Xh=a6(b.clone());a.jk=null;a.F=c;e&&(a.oD=!1);uFa(a,d)},uFa=function(a,b){a.Rl=(0,g.E)();
D6(a);a.Ti=a.Xh.clone();b6(a.Ti,"t",a.G);a.zo=0;a.dd=a.o.Bt(a.o.lo()?b:null);0<a.ju&&(a.zr=new w6((0,g.x)(a.jE,a,a.dd),a.ju));a.B.ma(a.dd,"readystatechange",a.aO);var c=a.Ej?g.Xb(a.Ej):{};a.jk?(a.ts="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.dd.send(a.Ti,a.ts,a.jk,c)):(a.ts="GET",a.oD&&!g.xe&&(c.Connection="close"),a.dd.send(a.Ti,a.ts,null,c));a.o.Xf(1)},yFa=function(a,b,c){for(var d=!0;!a.kj&&a.zo<c.length;){var e=wFa(a,c);
if(e==E6){4==b&&(a.li=4,F6(15),d=!1);break}else if(e==xFa){a.li=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.li=1,F6(17),d=!1);a.gg=a.gg&&d;d||(H6(a),I6(a))},wFa=function(a,b){var c=a.zo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return xFa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.zo=d+c;return e},AFa=function(a,b){a.Rl=(0,g.E)();
D6(a);var c=b?window.location.hostname:"";a.Ti=a.Xh.clone();$5(a.Ti,"DOMAIN",c);$5(a.Ti,"t",a.G);try{a.mg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.li=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in zFa)h=J6[l]=zFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.ic("b/12014412"),d+"</body></html>");a.mg.open();a.mg.write(g.ad(c));a.mg.close();a.mg.parentWindow.m=(0,g.x)(a.oN,a);a.mg.parentWindow.d=(0,g.x)(a.vC,a,!0);a.mg.parentWindow.rpcClose=(0,g.x)(a.vC,a,!1);c=a.mg.createElement("DIV");a.mg.parentWindow.document.body.appendChild(c);d=g.Jc(a.Ti.toString());d=g.ld(g.Fc(d));d=g.ed(g.ic("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.o.Xf(1)},D6=function(a){a.hx=(0,g.E)()+a.C;
BFa(a,a.C)},BFa=function(a,b){if(null!=a.fm)throw Error("WatchDog timer not null");
a.fm=K6((0,g.x)(a.zN,a),b)},L6=function(a){a.fm&&(g.v.clearTimeout(a.fm),a.fm=null)},I6=function(a){a.o.Bz()||a.kj||a.o.Xp(a)},H6=function(a){L6(a);
g.Ue(a.zr);a.zr=null;a.u.stop();g.kza(a.B);if(a.dd){var b=a.dd;a.dd=null;b.abort();b.dispose()}a.mg&&(a.mg=null)},G6=function(a,b){try{a.o.mC(a,b),a.o.Xf(4)}catch(c){}},DFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;CFa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){DFa(a,b,c,d,f)},f)})}},CFa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
QEa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},EFa=function(a){this.o=a;
this.u=new z6},FFa=function(a){var b=N6(a.o,a.sm,"/mail/images/cleardot.gif");
a6(b);DFa(b.toString(),5E3,(0,g.x)(a.xF,a),3,2E3);a.Xf(1)},P6=function(a){var b=a.o.N;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.ze=new B6(a,void 0,void 0,void 0),a.ze.Ej=a.hu,b=a.o,b=N6(b,b.lo()?a.Zm:null,a.iu),F6(5),!g.ve||g.Yd(10))b6(b,"TYPE","xmlhttp"),C6(a.ze,b,!1,a.Zm,!1);else{b6(b,"TYPE","html");var c=a.ze;a=!!a.Zm;c.Yl=3;c.Xh=a6(b.clone());AFa(c,a)}},Q6=function(a){g.xf.call(this);
this.headers=new g.on;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.N="";this.F=0;this.B="";this.C=this.Z=this.I=this.Y=!1;this.G=0;this.M=null;this.fa="";this.S=this.X=!1},GFa=function(a){return g.ve&&g.Xd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},HFa=function(a){return"content-type"==a.toLowerCase()},JFa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;IFa(a);R6(a)},IFa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},LFa=function(a){if(a.A&&"undefined"!=typeof g.B1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.ig(a.iC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.N));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!KFa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";IFa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){MFa(a);
var c=a.o,d=a.U[0]?g.Na:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},MFa=function(a){a.o&&a.S&&(a.o.ontimeout=null);
a.M&&(g.v.clearTimeout(a.M),a.M=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.N+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.N=null!=b?b:null;this.F=c||!1},NFa=function(a,b){this.o=a;
this.map=b;this.context=null},PFa=function(a){g.We.call(this,"statevent",a)},QFa=function(a,b,c,d){g.We.call(this,"timingevent",a);
this.size=b;this.bo=d},RFa=function(a){g.We.call(this,"serverreachability",a)},UFa=function(a){SFa(a);
if(3==a.o){var b=a.Hn++,c=a.Gp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Yl=2;b.Xh=a6(c.clone());QEa(new Image,b.Xh.toString());b.Rl=(0,g.E)();D6(b)}TFa(a)},VFa=function(a){a.VF(1,0);
a.Gp=N6(a,null,a.gu);X6(a)},SFa=function(a){a.Zh&&(a.Zh.abort(),a.Zh=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Yg&&(g.v.clearTimeout(a.Yg),a.Yg=null);Y6(a);a.pe&&(a.pe.cancel(),a.pe=null);a.di&&(g.v.clearTimeout(a.di),a.di=null)},WFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new NFa(a.WJ++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.pe||a.di||(a.di=K6((0,g.x)(a.uC,a),0),a.Sk=0)},YFa=function(a,b){if(1==a.o){if(!b){a.Hn=Math.floor(1E5*Math.random());
var c=a.Hn++,d=new B6(a,"",c,void 0);d.Ej=a.Zk;var e=Z6(a),f=a.Gp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);vFa(d,f,e);a.pe=d;a.o=2}}else 3==a.o&&(b?XFa(a,b):0==a.u.length||a.pe||XFa(a))},XFa=function(a,b){if(b)if(6<a.lj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Hn-1;var d=Z6(a)}else c=b.I,d=b.jk;else c=a.Hn++,d=Z6(a);var e=a.Gp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.rl);W6(a,e);c=new B6(a,a.A,c,a.Sk+1);c.Ej=a.Zk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.pe=c;vFa(c,e,d)},W6=function(a,b){if(a.Gd){var c=a.Gd.bz();
c&&g.Gb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.lj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.lj?e:f-d;try{g.Gb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},ZFa=function(a){a.Ec||a.Yg||(a.G=1,a.Yg=K6((0,g.x)(a.tC,a),0),a.Gk=0)},$6=function(a){if(a.Ec||a.Yg||3<=a.Gk)return!1;
a.G++;a.Yg=K6((0,g.x)(a.tC,a),$Fa(a,a.Gk));a.Gk++;return!0},O6=function(a,b,c){a.qs=c;
a.wg=b.qh;a.F||VFa(a)},Y6=function(a){null!=a.pj&&(g.v.clearTimeout(a.pj),a.pj=null)},$Fa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Gd&&(c=null);var d=(0,g.x)(a.HO,a);c||(c=new g.rn("//www.google.com/images/cleardot.gif"),a6(c));CFa(c.toString(),1E4,d)}else F6(2);aGa(a,b)},aGa=function(a,b){a.o=0;
a.Gd&&a.Gd.ty(b);TFa(a);SFa(a)},TFa=function(a){a.o=0;
a.wg=-1;if(a.Gd)if(0==a.B.length&&0==a.u.length)a.Gd.jt();else{g.ub(a.B);var b=g.ub(a.u);a.B.length=0;a.u.length=0;a.Gd.jt(b)}},N6=function(a,b,c){var d=g.zn(c);
if(""!=d.o)b&&g.tn(d,b+"."+d.o),g.un(d,d.B);else{var e=window.location;d=UEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Mm&&g.Gb(a.Mm,function(f,h){$5(d,h,f)});
$5(d,"VER",a.lj);W6(a,d);return d},K6=function(a,b){if(!g.Sa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new PFa(b7,a))},bGa=function(){},cGa=function(){this.o=[];
this.u=[]},dGa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.o=new g.G(this.hN,0,this);g.C(this,this.o);this.Jd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.M=a;this.F=b;this.A=new g.so;this.u=new c7(this.mO,this);this.o=null;this.Rc=!1;this.C=null;this.N="";this.I=this.B=0;this.G=[];this.U=c;this.S=d},eGa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.qs,sessionId:a.o.A,arrayId:a.o.rl}},fGa=function(a,b){a.I=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.o&&YFa(a.o),UFa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},e7=function(a){if(a.o){var b=a.S(),c=a.o.Zk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.Zk=c}},gGa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Jd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Xa(a.B,d,!0),onError:g.Xa(a.A,e),Te:g.Xa(a.C,e)};c&&(a.Hb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Oq(b,a)},kGa=function(){var a=hGa;
iGa();j7.push(a);jGa(j7)},k7=function(a,b){iGa();
var c=j7,d=lGa(a,String(b));g.ob(c)?mGa(d):(jGa(c),g.z(c,function(e){e(d)}))},iGa=function(){j7||(j7=g.Ma("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},mGa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},jGa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.z(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},lGa=function(a,b){var c=((0,g.E)()-nGa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.N.call(this);
this.F=a;this.screens=[]},oGa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},pGa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ie(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=oGa(a,b[d])||c;return c},qGa=function(a,b){var c=a.screens.length;
a.screens=g.Ie(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},rGa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.GG,a),(0,g.x)(a.FG,a))}},q7=function(a){var b=$Ea(fFa());
b=g.Ie(b,function(c){return!c.uuid});
return pGa(a,b)},s7=function(a,b){hFa(g.Oc(a.screens,YEa));
b&&gFa()},u7=function(a,b){g.N.call(this);
this.F=b;var c=g.At("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.nb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.fl(this.o))},sGa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.fl(a.o)),a.o=b,a.R("screenChange"));tGa(a)},w7=function(a){isNaN(a.A)||g.fp(a.A);
a.A=g.dp((0,g.x)(a.ew,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},uGa=function(a){var b={};
g.z(a.F(),function(c){c.token?b[c.token]=c.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},tGa=function(a){a=g.Nb(g.Hb(a.o,function(b){return b}));
g.Cb(a);a.length?g.zt("yt-remote-online-screen-ids",a.join(","),60):g.Bt("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};vGa(this)},xGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Le();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);sGa(a.o,l,function(m){e(m?l:null)})}else c?wGa(a,c,(0,g.x)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));sGa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},yGa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},wGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Hb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Oq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},zGa=function(a){a.screens=a.u.Le();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},vGa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.NG,a));zGa(a);a.A=$Ea(g.At("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.x)(a.Le,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.zt("yt-remote-automatic-screen-cache",g.Oc(a.A,YEa)));z7(a);a.B[b.uuid]=b.id;g.zt("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.At("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.N.call(this);
this.U=c;this.I=a;this.o=b;this.G=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.oP,this);this.B=(0,g.x)(this.HN,this);this.A=g.dp((0,g.x)(function(){AGa(this,null)},this),12E4)},BGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.fl(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Na,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.fl(b))},AGa=function(a,b){g.fp(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.mr,a),d=(0,g.x)(a.Se,a);a.uz(b,c,d,5)}}else a.Se(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.F=null;this.N="";this.T=c;this.M=null;this.C=g.Na;this.B=NaN;this.S=(0,g.x)(this.rP,this);this.u=g.Na},CGa=function(a){a.u=a.I.qE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Na;
this.mr(b)},a),(0,g.x)(function(b){this.u=g.Na;
this.Se(b)},a))},DGa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;jFa()&&(b.env_useStageMdx=1);return g.Fd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.dp((0,g.x)(this.sl,this,null),150)},F7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.vM,this)},EGa=function(a,b){return b?g.jb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},hGa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Ue(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.o):a.R("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.rC,a,b)),b.getScreen()?a.R("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.sl(null)):a.R("yt-remote-cast2-session-change",null))},FGa=function(a){var b=a.u.pE(),c=a.o&&a.o.o;
a=g.Oc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=EGa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},LGa=function(a,b,c,d,e,f,h){GGa()?HGa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?IGa(a,c):(window.__onGCastApiAvailable=function(l,m){l?IGa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.Bt("yt-remote-cast-available"),g.Bt("yt-remote-cast-receiver"),JGa(),c(!1))},d?g.pp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?qFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(pFa(),t6(KGa.map(nFa))))):J7("Cannot initialize because not running Chrome")},JGa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);MGa(!1);g.lp(O7);O7.length=0},P7=function(){return!!g.At("yt-remote-cast-installed")},NGa=function(){var a=g.At("yt-remote-cast-receiver");
return a?a.friendlyName:null},OGa=function(){J7("clearCurrentReceiver");
g.Bt("yt-remote-cast-receiver")},PGa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.kp("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},GGa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.tx||a},QGa=function(a,b){N7().init(a,b)},HGa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.zt("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.zt("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.zt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.Bt("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Ma("yt.mdx.remote.cloudview.instance_")},IGa=function(a,b){M7(!0);
K7(!1);QGa(a,function(c){c?(MGa(!0),g.mp("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.Bt("yt-remote-cast-available"),g.Bt("yt-remote-cast-receiver"),JGa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.zt("yt-remote-cast-installed",a)},Q7=function(){return!!g.Ma("yt.mdx.remote.cloudview.apiReady_")},MGa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.xg=!1;this.N=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.xg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.N=0;a.B=NaN;a.A=!1},V7=function(a){return a.sb()?((0,g.E)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.E)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Yb(a.o);b.hasPrevious=a.xg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.N;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new cGa;this.A=this.u=null;this.N=(0,g.x)(this.EK,this);this.G=(0,g.x)(this.Ln,this);this.I=(0,g.x)(this.DK,this);this.M=(0,g.x)(this.MK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.jx,this),RGa(this))):c=3;0!=c&&(b?this.jx(c):g.dp((0,g.x)(function(){this.jx(c)},this),0));
var d=PGa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.M)},b8=function(a){return new T7(a.B.getPlayerContextData())},RGa=function(a){g.z("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Xa(this.rM,b),this))},a)},SGa=function(a){g.z(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){SGa(a);
a.B.setPlayerContextData(Z7(b));RGa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.N),a.A.removeMediaListener(a.G),a.Ln(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.N),a.A.addMediaListener(a.G),a.A.media.length&&a.Ln(a.A.media[0]))},TGa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.N.call(this);
this.C=NaN;this.S=!1;this.I=this.G=this.N=this.M=NaN;this.U=[];this.B=this.F=this.A=this.jb=this.o=null;this.Y=a;this.U.push(g.Ap(window,"beforeunload",(0,g.x)(this.zG,this)));this.u=[];this.jb=new T7;this.T=b.id;this.o=UGa(this,c);this.o.subscribe("handlerOpened",this.IK,this);this.o.subscribe("handlerClosed",this.FK,this);this.o.subscribe("handlerError",this.GK,this);this.o.subscribe("handlerMessage",this.HK,this);gGa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.jb.videoId;
g.Ct()&&g.zt("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},UGa=function(a,b){return new d7(h7(a.Y,"/bc"),b,!1,function(){return a.mE()})},j8=function(a,b){a.R("proxyStateChange",b)},VGa=function(a){a.C=g.dp((0,g.x)(function(){i8("Connecting timeout");
this.Ok(1)},a),2E4)},k8=function(a){g.fp(a.C);
a.C=NaN},l8=function(a){g.fp(a.M);
a.M=NaN},WGa=function(a){m8(a);
a.N=g.dp((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.fp(a.N);
a.N=NaN},YGa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.rz()&&a.jb.reset(),j8(a,1),n8(a,"getNowPlaying"),XGa(a)):a.Ok(1)},ZGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Tb(b.params)?a.jb.o=null:a.jb.o=b.params,a.R("remotePlayerChange"))},$Ga=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;Y7(a.jb,c,d);a.R("remoteQueueChange")},bHa=function(a,b){b.params=b.params||{};
$Ga(a,b);aHa(a,b);a.R("autoplayDismissed")},aHa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.jb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jb.playerState&&(c=-1E3);a.jb.playerState=c;c=Number(b.params.loadedTime);a.jb.N=isNaN(c)?0:c;c=Number(b.params.duration);a.jb.I=isNaN(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.jb.playerState?WGa(a):m8(a);a.R("remotePlayerChange")},cHa=function(a,b){if(-1E3!=
a.jb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.jb,isNaN(c)?0:c);a.R("remotePlayerChange")}},dHa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=parseInt(b.params.volume,10);a.jb.muted=c;a.R("remotePlayerChange")},eHa=function(a,b){a.F=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},fHa=function(a,b){var c="true"==b.params.hasNext;
a.jb.xg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.R("previousNextChange")},XGa=function(a){g.fp(a.I);
a.I=g.dp((0,g.x)(a.Ok,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.fl(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Id=a;this.o=[];this.o.push(this.Id.$_s("screenChange",(0,g.x)(this.mP,this)));this.o.push(this.Id.$_s("onlineScreenChange",(0,g.x)(this.VL,this)))},kHa=function(a,b){b=g.K("MDX_CONFIG")||b;
bFa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),jFa()&&(p8.o="/api/loungedev"));q8||(q8=g.Ma("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));gHa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);LGa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Ma("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.fl(b)),u8.push(g.kp("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.kp("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.kp("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.kp("yt-remote-cast2-session-change",hHa)),u8.push(g.kp("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),OGa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.Uo("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.fl(e)),iHa(e),c.start(),s8()||jHa())},mHa=function(){var a=lHa();
P7()&&g.At("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},lHa=function(){var a=r8().Id.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return aFa(a)},A8=function(){var a=nHa();
!a&&P7()&&NGa()&&(a={key:"cast-selector-receiver",name:NGa()});return a},nHa=function(){var a=lHa(),b=y8();
b||(b=w8());return g.jb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Le();return m6(b,a)},hHa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Ma("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ma("yt.mdx.remote.currentScreenId_")},oHa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},pHa=function(){return g.Ma("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ma("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||oHa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&(g.z(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.Ct();
if(!a)return null;var b=r8();if(!b)return null;b=b.Le();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{oHa(a.id);var c=new h8(p8,a,x8());c.connect(b,pHa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},jHa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),OGa(),t8("Skipping connecting because no session screen found."))},gHa=function(){var a=x8();
if(g.Tb(a)){a=p6();var b=g.At("yt-remote-session-name")||"",c=g.At("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ma("yt.mdx.remote.channelParams_")||{}},iHa=function(a){a?(g.zt("yt-remote-session-app",a.app),g.zt("yt-remote-session-name",a.name)):(g.Bt("yt-remote-session-app"),g.Bt("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.module=a;this.H=b;this.Ya=c;this.events=new g.Cs(this);this.N=this.events.L(this.H,"onVolumeChange",this.TB);this.B=!1;this.suggestion=null;this.C=new g.MI(64);this.o=new g.G(this.xD,500,this);this.u=new g.G(this.yD,1E3,this);this.G=new v6(this.RO,0,this);this.A={};this.I=new g.G(this.ZD,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.M=g.Na;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.wL);this.events.L(b,"captionschanged",this.CK);this.events.L(b,"captionssettingschanged",
this.BD);this.events.L(b,"videoplayerreset",this.qr);this.events.L(b,"mdxautoplaycancel",function(){d.Ya.Ly()});
a=this.Ya;a.ha();a.subscribe("proxyStateChange",this.lC,this);a.subscribe("remotePlayerChange",this.Rn,this);a.subscribe("remoteQueueChange",this.qr,this);a.subscribe("previousNextChange",this.hC,this);a.subscribe("nowAutoplaying",this.dC,this);a.subscribe("autoplayDismissed",this.DB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.BD();this.qr();this.Rn()},qHa=function(a){a.Xb(0);
a.o.stop();a.Pc(new g.MI(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.$b(c,b));a.Ya.nE(a.H.getVideoData(1).videoId,c);a.A=b8(a.Ya).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Ya.playVideo(c.videoId,b,d,e,c.playerParams,c.Ne,OEa(c));a.Pc(new g.MI(1))},rHa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Tz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.Ya).videoId===a.H.getVideoData(1).videoId},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",ca:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",ca:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.yO(this,250);this.learnMoreButton=
this.ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ba("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},N8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",ca:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",ca:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.yO(this,250);this.cancelButton=this.ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ba("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},O8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.AO()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.yO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);sHa(this,g.WD(a))},sHa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.xD("Error on $RECEIVER_NAME",c):b.sb()||g.W(b,4)?g.xD("Playing on $RECEIVER_NAME",c):g.xD("Connected to $RECEIVER_NAME",c);a.na("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.gS.call(this,"Play on",0,a,b);
this.H=a;this.Si={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.dO.call(this,a);
this.Sf={key:k6(),name:"This computer"};this.pg=null;this.subscriptions=[];this.Nv=this.Ya=null;this.Si=[this.Sf];this.bi=this.Sf;this.Ub=new g.MI(64);this.lA=0;this.kd=-1;this.vl=null;this.Sn=this.zq=!1;this.ik=this.Nl=null;if(!g.kz(this.player.O())){a=this.player;var b=g.qN(a);b&&(b=b.Bj())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.QN(a,b.element,4);this.Nl=new N8;g.C(this,this.Nl);g.QN(a,this.Nl.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.vl=new M8,g.C(this,this.vl),g.QN(a,this.vl.element,4));this.Sn=!!w8();this.zq=!!g.At("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.ik&&(a.player.removeEventListener("presentingplayerstatechange",a.ik),a.ik=null)},tHa=function(a,b,c){a.Ub=c;
a.player.R("presentingplayerstatechange",new g.JK(c,b))},uHa=function(a,b,c){var d=!1;
1===b?d=!a.Sn:2===b&&(d=!a.zq);d&&g.LK(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.bi.key)if(b.key===a.Sf.key)B8();
else{if(a.vl&&!a.zq&&b!==a.Sf&&"cast-selector-receiver"!==b.key&&g.tz(a.player.O()))vHa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Sn||!a.Nl);(c?0:g.tz(a.player.O())||g.xz(a.player.O()))&&wHa(a)}a.bi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Aa(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ne,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=OEa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.fl(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Le(),(c=m6(c,b.key))&&C8(c,1))}},wHa=function(a){g.WD(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){uHa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.Nl&&a.Nl.Nb();z8()||(G8=!0)},vHa=function(a){g.WD(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){uHa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.vl&&a.vl.Nb();z8()||(G8=!0)},zFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},xHa={},XEa={SP:"atp",JS:"ska",uS:"que",JR:"mus",IS:"sus",RQ:"dsp",BS:"seq"},s6,o6="",oFa=kFa("loadCastFramework")||kFa("loadCastApplicationFramework"),KGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Za(v6,g.B);g.k=v6.prototype;g.k.wG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Jd:this.Ka=g.ig(this.C,this.Jd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.W=function(){this.stop();v6.uc.W.call(this)};
g.k.xG=function(){this.A?(this.Ka=g.ig(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.B);g.k=w6.prototype;g.k.zA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.W=function(){g.B.prototype.W.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},sFa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Za(rFa,A6);T8=new rFa;g.k=B6.prototype;g.k.Ej=null;g.k.gg=!1;g.k.fm=null;g.k.hx=null;g.k.Rl=null;g.k.Yl=null;g.k.Xh=null;g.k.Ti=null;g.k.jk=null;g.k.dd=null;g.k.zo=0;g.k.mg=null;g.k.ts=null;g.k.li=null;g.k.an=-1;g.k.oD=!0;g.k.kj=!1;g.k.ju=0;g.k.zr=null;var xFa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.aO=function(a){a=a.target;var b=this.zr;b&&3==S6(a)?b.zA():this.jE(a)};
g.k.jE=function(a){try{if(a==this.dd)a:{var b=S6(this.dd),c=this.dd.F,d=this.dd.getStatus();if(g.ve&&!g.Yd(10)||g.xe&&!g.Xd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Rh&&!U6(this.dd))break a;this.kj||4!=b||7==c||(8==c||0>=d?this.o.Xf(3):this.o.Xf(2));L6(this);var e=this.dd.getStatus();this.an=e;var f=U6(this.dd);(this.gg=200==e)?(4==b&&H6(this),this.F?(yFa(this,b,f),g.Rh&&this.gg&&3==b&&(this.B.ma(this.u,"tick",this.UN),this.u.start())):G6(this,f),this.gg&&!this.kj&&(4==b?this.o.Xp(this):(this.gg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.li=3,F6(13)):(this.li=0,F6(14)),H6(this),I6(this))}}catch(h){this.dd&&U6(this.dd)}finally{}};
g.k.UN=function(){var a=S6(this.dd),b=U6(this.dd);this.zo<b.length&&(L6(this),yFa(this,a,b),this.gg&&4!=a&&D6(this))};
g.k.oN=function(a){K6((0,g.x)(this.nN,this,a),0)};
g.k.nN=function(a){this.kj||(L6(this),G6(this,a),D6(this))};
g.k.vC=function(a){K6((0,g.x)(this.mN,this,a),0)};
g.k.mN=function(a){this.kj||(H6(this),this.gg=a,this.o.Xp(this),this.o.Xf(4))};
g.k.cancel=function(){this.kj=!0;H6(this)};
g.k.zN=function(){this.fm=null;var a=(0,g.E)();0<=a-this.hx?(2!=this.Yl&&this.o.Xf(3),H6(this),this.li=2,F6(18),I6(this)):BFa(this,this.hx-a)};
g.k.getLastError=function(){return this.li};g.k=EFa.prototype;g.k.hu=null;g.k.ze=null;g.k.Ar=!1;g.k.Cz=null;g.k.Ep=null;g.k.Lu=null;g.k.iu=null;g.k.mf=null;g.k.qh=-1;g.k.Zm=null;g.k.sm=null;g.k.connect=function(a){this.iu=a;a=N6(this.o,null,this.iu);F6(3);this.Cz=(0,g.E)();var b=this.o.I;null!=b?(this.Zm=b[0],(this.sm=b[1])?(this.mf=1,FFa(this)):(this.mf=2,P6(this))):(b6(a,"MODE","init"),this.ze=new B6(this,void 0,void 0,void 0),this.ze.Ej=this.hu,C6(this.ze,a,!1,null,!0),this.mf=0)};
g.k.xF=function(a){if(a)this.mf=2,P6(this);else{F6(4);var b=this.o;b.wg=b.Zh.qh;a7(b,9)}a&&this.Xf(2)};
g.k.Bt=function(a){return this.o.Bt(a)};
g.k.abort=function(){this.ze&&(this.ze.cancel(),this.ze=null);this.qh=-1};
g.k.Bz=function(){return!1};
g.k.mC=function(a,b){this.qh=a.an;if(0==this.mf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.wg=this.qh;a7(c,2);return}this.Zm=c[0];this.sm=c[1]}else c=this.o,c.wg=this.qh,a7(c,2);else if(2==this.mf)if(this.Ar)F6(7),this.Lu=(0,g.E)();else if("11111"==b){if(F6(6),this.Ar=!0,this.Ep=(0,g.E)(),c=this.Ep-this.Cz,!g.ve||g.Yd(10)||500>c)this.qh=200,this.ze.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Ep=this.Lu=(0,g.E)(),this.Ar=!1};
g.k.Xp=function(){this.qh=this.ze.an;if(this.ze.gg)0==this.mf?this.sm?(this.mf=1,FFa(this)):(this.mf=2,P6(this)):2==this.mf&&((!g.ve||g.Yd(10)?!this.Ar:200>this.Lu-this.Ep)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.mf?F6(9):2==this.mf&&F6(10);var a=this.o;this.ze.getLastError();a.wg=this.qh;a7(a,2)}};
g.k.lo=function(){return this.o.lo()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Xf=function(a){this.o.Xf(a)};g.Za(Q6,g.xf);var KFa=/^https?$/i,yHa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.N+"; newUri="+a);b=b?b.toUpperCase():"GET";this.N=a;this.B="";this.F=0;this.ga=b;this.Y=!1;this.A=!0;this.o=this.T?tFa(this.T):tFa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.iC,this);try{d6(T6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));JFa(this,f);return}a=c||
"";var e=this.headers.clone();d&&TEa(d,function(f,h){e.set(h,f)});
d=g.jb(e.kf(),HFa);c=g.v.FormData&&a instanceof g.v.FormData;!g.nb(yHa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.X&&(this.o.withCredentials=this.X);try{MFa(this),0<this.G&&(this.S=GFa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.S)),this.S?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Dz,this)):this.M=g.ig(this.Dz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),JFa(this,f)}};
g.k.Dz=function(){"undefined"!=typeof g.B1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.W=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.uc.W.call(this)};
g.k.iC=function(){this.ha()||(this.Z||this.I||this.C?LFa(this):this.uM())};
g.k.uM=function(){LFa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Zk=null;g.k.Mm=null;g.k.pe=null;g.k.Ec=null;g.k.gu=null;g.k.Gp=null;g.k.jy=null;g.k.Wp=null;g.k.Hn=0;g.k.WJ=0;g.k.Gd=null;g.k.di=null;g.k.Yg=null;g.k.pj=null;g.k.Zh=null;g.k.qs=null;g.k.rl=-1;g.k.kA=-1;g.k.wg=-1;g.k.Sk=0;g.k.Gk=0;g.k.lj=8;var b7=new g.xf;g.Za(PFa,g.We);g.Za(QFa,g.We);g.Za(RFa,g.We);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.gu=b;this.Mm=c||{};d&&void 0!==e&&(this.Mm.OSID=d,this.Mm.OAID=e);this.F?(K6((0,g.x)(this.Ay,this,a),100),VFa(this)):this.Ay(a)};
g.k.Ay=function(a){this.Zh=new EFa(this);this.Zh.hu=this.Zk;this.Zh.u=this.C;this.Zh.connect(a)};
g.k.Bz=function(){return 0==this.o};
g.k.uC=function(a){this.di=null;YFa(this,a)};
g.k.tC=function(){this.Yg=null;this.Ec=new B6(this,this.A,"rpc",this.G);this.Ec.Ej=this.Zk;this.Ec.ju=0;var a=this.jy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.qs?"0":"1");$5(a,"AID",this.rl);W6(this,a);if(!g.ve||g.Yd(10))$5(a,"TYPE","xmlhttp"),C6(this.Ec,a,!0,this.Wp,!1);else{$5(a,"TYPE","html");var b=this.Ec,c=!!this.Wp;b.Yl=3;b.Xh=a6(a.clone());AFa(b,c)}};
g.k.mC=function(a,b){if(0!=this.o&&(this.Ec==a||this.pe==a))if(this.wg=a.an,this.pe==a&&3==this.o)if(7<this.lj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Yg){if(this.Ec)if(this.Ec.Rl+3E3<this.pe.Rl)Y6(this),this.Ec.cancel(),this.Ec=null;else break a;$6(this);F6(19)}}else this.kA=c[1],0<this.kA-this.rl&&37500>c[2]&&this.qs&&0==this.Gk&&!this.pj&&(this.pj=K6((0,g.x)(this.yK,this),6E3));else a7(this,11)}else b!=xHa.qQ.o&&a7(this,11);else if(this.Ec==
a&&Y6(this),!g.qc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.rl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Wp=e[2],e=e[3],null!=e?this.lj=e:this.lj=6,this.o=3,this.Gd&&this.Gd.vy(),this.jy=N6(this,this.lo()?this.Wp:null,this.gu),ZFa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Gd&&this.Gd.uy(e),this.Gk=0)}}};
g.k.yK=function(){null!=this.pj&&(this.pj=null,this.Ec.cancel(),this.Ec=null,$6(this),F6(20))};
g.k.Xp=function(a){if(this.Ec==a){Y6(this);this.Ec=null;var b=2}else if(this.pe==a)this.pe=null,b=1;else return;this.wg=a.an;if(0!=this.o)if(a.gg)1==b?(b=(0,g.E)()-a.Rl,b7.dispatchEvent(new QFa(b7,a.jk?a.jk.length:0,b,this.Sk)),X6(this),this.B.length=0):ZFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.wg)){if(d=1==b)this.pe||this.di||1==this.o||2<=this.Sk?d=!1:(this.di=K6((0,g.x)(this.uC,this,a),$Fa(this,this.Sk)),this.Sk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.VF=function(a){if(!g.nb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.HO=function(a){a?F6(2):(F6(1),aGa(this,8))};
g.k.Bt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.X=!1;return a};
g.k.isActive=function(){return!!this.Gd&&this.Gd.isActive(this)};
g.k.Xf=function(a){b7.dispatchEvent(new RFa(b7,a))};
g.k.lo=function(){return!(!g.ve||g.Yd(10))};
g.k=bGa.prototype;g.k.vy=function(){};
g.k.uy=function(){};
g.k.ty=function(){};
g.k.jt=function(){};
g.k.bz=function(){return{}};
g.k.isActive=function(){return!0};g.k=cGa.prototype;g.k.isEmpty=function(){return g.ob(this.o)&&g.ob(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.nb(this.o,a)||g.nb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.pza)(b,a);0<=c?(g.qb(b,c),b=!0):b=!1;return b||g.rb(this.u,a)};
g.k.Xd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Za(c7,g.B);g.k=c7.prototype;g.k.hN=function(){this.Jd=Math.min(3E5,2*this.Jd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Jd+15E3*Math.random();this.o.gb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Jd=5E3};g.Za(d7,bGa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ji=function(a){return this.A.Fj(a)};
g.k.R=function(a,b){return this.A.R.apply(this.A,arguments)};
g.k.dispose=function(){this.Rc||(this.Rc=!0,g.Ue(this.A),fGa(this),g.Ue(this.u),this.u=null,this.S=function(){return""})};
g.k.ha=function(){return this.Rc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.N="";this.u.stop();this.C=a||null;this.B=b||0;a=this.M+"/test";b=this.M+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Gd=null);d.Gd=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.A,e.rl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.$b(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&(e7(this),WFa(this.o,c))};
g.k.vy=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)WFa(this.o,a[b])}this.R("handlerOpened")};
g.k.ty=function(a){var b=2==a&&401==this.o.wg;4==a||b||this.u.start();this.R("handlerError",a)};
g.k.jt=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.bz=function(){var a={v:2};this.N&&(a.gsessionid=this.N);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.$b(a,this.C);return a};
g.k.uy=function(a){"S"==a[0]?this.N=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),UFa(this.o)):this.R("handlerMessage",new dGa(a[0],a[1]))};
g.k.mO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.pe&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var nGa=(0,g.E)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Za(o7,g.N);o7.prototype.Le=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.N);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.oE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.fp(this.Ka),this.Ka=NaN)};
g.k.W=function(){this.stop();g.N.prototype.W.call(this)};
g.k.oE=function(){this.Ka=NaN;this.o=g.Oq(h7(this.F,"/pairing/get_screen"),{method:"POST",Hb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.kP,this),onError:(0,g.x)(this.jP,this),Te:(0,g.x)(this.lP,this)})};
g.k.kP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.R("pairingComplete",new g6(c))};
g.k.jP=function(a){this.o=null;a.status&&404==a.status?this.u>=zHa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=zHa[this.u],this.Ka=g.dp((0,g.x)(this.oE,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.k.lP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var zHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Za(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.R("screenChange");!g.At("yt-remote-lounge-token-expiration")&&rGa(this);g.fp(this.o);this.o=g.dp((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);oGa(this,a);s7(this,!1);this.R("screenChange");b(a);a.token||rGa(this)};
g.k.remove=function(a,b){var c=q7(this);qGa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.k.ks=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.k.W=function(){g.fp(this.o);r7.uc.W.call(this)};
g.k.GG=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.FG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.N);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.At("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?w7(this):(this.B=(0,g.E)()+3E5,g.zt("yt-remote-fast-check-period",this.B),this.ew())};
g.k.isEmpty=function(){return g.Tb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Hb(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.W=function(){g.fp(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.W.call(this)};
g.k.ew=function(){g.fp(this.A);this.A=NaN;this.u&&this.u.abort();var a=uGa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Nb(a).join(",")},(0,g.x)(this.RM,this,a),(0,g.x)(this.QM,this))}else v7(this,{}),w7(this)};
g.k.RM=function(a,b){this.u=null;var c=g.Nb(uGa(this));if(g.Db(c,g.Nb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.qc("Changing Screen set during request."),this.ew()};
g.k.QM=function(a){this.qc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.qc=function(a){k7("OnlineScreenService",a)};g.Za(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.R("screenChange"),this.o.isEmpty()||this.R("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.ks=function(a,b,c,d){this.u.contains(a)?this.u.ks(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Le=function(a){return a?this.screens:g.tb(this.screens,g.Ie(this.A,function(b){return!this.contains(b)},this))};
g.k.pE=function(){return g.Ie(this.Le(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.qE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Ue(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Ue(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.nP=function(a,b,c,d){g.Oq(h7(this.C,"/pairing/get_screen"),{method:"POST",Hb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||yGa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);yGa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Te:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.W=function(){g.Ue(this.u);g.Ue(this.o);x7.uc.W.call(this)};
g.k.NG=function(){zGa(this);this.R("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Za(A7,g.N);g.k=A7.prototype;g.k.getScreen=function(){return this.G};
g.k.mr=function(a){this.G=a;this.R("sessionScreen",this.G)};
g.k.Se=function(a){this.ha()||(a&&B7(this,""+a),this.G=null,this.R("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.sE=function(){return null};
g.k.pw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.W=function(){this.pw("");A7.uc.W.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.ow=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);BGa(this)};
g.k.sl=function(a){this.info("launchWithParams no-op for Cast: "+g.fl(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Se()},this),(0,g.x)(function(){this.Se(Error("Failed to stop receiver app."))},this)):this.Se(Error("Stopping cast device witout session."))};
g.k.pw=function(){};
g.k.W=function(){this.info("disposeInternal");g.fp(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.W.call(this)};
g.k.HN=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Ua(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.fl(c));switch(d){case "mdxSessionStatus":AGa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.uz=function(a,b,c,d){xGa(this.I,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.dp((0,g.x)(this.uz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.sE=function(){return this.u};
g.k.oP=function(a){this.ha()||a||(B7(this,"Cast session died."),this.Se())};g.t(D7,A7);g.k=D7.prototype;g.k.ow=function(a){this.A=a;this.A.addUpdateListener(this.S)};
g.k.sl=function(a){this.M=a;this.C()};
g.k.stop=function(){this.u();this.u=g.Na;g.fp(this.B);this.A?this.A.stop((0,g.x)(this.Se,this,null),(0,g.x)(this.Se,this,"Failed to stop DIAL device.")):this.Se()};
g.k.W=function(){this.u();this.u=g.Na;g.fp(this.B);this.A&&this.A.removeUpdateListener(this.S);this.A=null;A7.prototype.W.call(this)};
g.k.rP=function(a){this.ha()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Na,this.Se())};
g.k.uu=function(a){this.N=k6();if(this.M){var b=new chrome.cast.DialLaunchResponse(!0,DGa(this));a(b);CGa(this)}else this.C=(0,g.x)(function(){g.fp(this.B);this.C=g.Na;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,DGa(this));a(c);CGa(this)},this),this.B=g.dp((0,g.x)(function(){this.C()},this),100)};
g.k.eH=function(a,b,c){xGa(this.I,this.F.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.mr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.uu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.uu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Se()};
E7.prototype.ow=function(){};
E7.prototype.sl=function(){g.fp(this.u);this.u=NaN;var a=m6(this.I.Le(),this.o.label);a?this.mr(a):this.Se(Error("No such screen"))};
E7.prototype.W=function(){g.fp(this.u);this.u=NaN;A7.prototype.W.call(this)};g.t(F7,g.N);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.pC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.RK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),kGa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.rE,this)),this.A=FGa(this),chrome.cast.setCustomReceivers(this.A,g.Na,(0,g.x)(function(h){this.qc("Failed to set initial custom receivers: "+g.fl(h))},this)),this.R("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.qc("Failed to initialize API: "+g.fl(h));
b(!1)},this))};
g.k.sO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Le(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=EGa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Na,(0,g.x)(function(e){this.qc("Failed to set initial custom receivers: "+g.fl(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.pw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.tO=function(a){this.ha()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.sl(a):this.qc("Setting connection data without a session")};
g.k.qP=function(){this.ha()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.pC,this),(0,g.x)(this.UM,this))};
g.k.W=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.rE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=hGa,b=g.Ma("yt.mdx.remote.debug.handlers_");g.rb(b||[],a);g.Ue(this.o);g.N.prototype.W.call(this)};
g.k.qc=function(a){k7("Controller",a)};
g.k.rC=function(a,b){this.o==a&&(b||I7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.k.vM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.R("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.k.RK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.eH,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.x)(b.uu,b))};
g.k.pC=function(a){if(!this.ha()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Le(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ue(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.rC,this,this.o)),this.o.sl(null));this.o.ow(a)}}};
g.k.pP=function(){return this.o?this.o.sE():null};
g.k.UM=function(a){this.ha()||(this.qc("Failed to estabilish a session: "+g.fl(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.zM=function(a){G7("Receiver availability updated: "+a);if(!this.ha()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.R("yt-remote-cast2-availability-change",H7(this))}};
g.k.rE=function(){this.ha()||(this.A=FGa(this),G7("Updating custom receivers: "+g.fl(this.A)),chrome.cast.setCustomReceivers(this.A,g.Na,(0,g.x)(function(){this.qc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.tO;F7.prototype.setConnectedScreenStatus=F7.prototype.sO;F7.prototype.stopSession=F7.prototype.qP;F7.prototype.getCastSession=F7.prototype.pP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.xg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.N=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.N);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Na,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Na,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.R("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Na,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.R("remotePlayerChange")}else c8(this,g.Xa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Na,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.R("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Xa(this.setVolume,a,b))};
g.k.nE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.fl(b.style),g.$b(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Xa(this.nE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Xa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.fl(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.vr=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Xa(this.vr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Xa(this.nextVideo,a,b))};
g.k.Ly=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.Ly)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.W=function(){SGa(this);this.B=null;this.C.clear();$7(this,null);g.N.prototype.W.call(this)};
g.k.jx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.ob(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.rM=function(a,b){this.R(a,b)};
g.k.EK=function(a){if(!a)this.Ln(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Ln=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),TGa(this),this.R("remotePlayerChange")};
g.k.DK=function(a){a?(TGa(this),this.R("remotePlayerChange")):this.Ln(null)};
g.k.Hw=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.MK=function(){var a=PGa();a&&$7(this,a)};
g.k.qc=function(a){k7("CP",a)};g.t(h8,g.N);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=h||0;this.jb.state=3;W7(this.jb,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.fl(l));this.o.connect({method:"setPlaylist",
params:g.fl(l)},a,eFa())}else i8("Connecting without params"),this.o.connect({},a,eFa());VGa(this)};
g.k.dispose=function(){this.ha()||(this.R("beforeDispose"),j8(this,3));g.N.prototype.dispose.call(this)};
g.k.W=function(){k8(this);m8(this);l8(this);g.fp(this.G);this.G=NaN;g.fp(this.I);this.I=NaN;this.A=null;g.Bp(this.U);this.U.length=0;this.o.dispose();g.N.prototype.W.call(this);this.B=this.F=this.u=this.jb=this.o=null};
g.k.zG=function(){this.Ok(2)};
g.k.IK=function(){i8("Channel opened");this.S&&(this.S=!1,l8(this),this.M=g.dp((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Ok(1)},this),15E3));
iFa(eGa(this.o),this.T)};
g.k.FK=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.GK=function(a){r6();isNaN(this.Vm())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.S=!0,i8("Channel error: "+a+" with reconnection in "+this.Vm()+" ms"),j8(this,2))};
g.k.HK=function(a){a.params?i8("Received: action="+a.action+", params="+g.fl(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=g.Oc(a,function(c){return new f6(c)});
a=!!g.jb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
YGa(this,a);break;case "loungeScreenDisconnected":g.sb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
YGa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.jb(this.u,function(c){return b?c.id==b.id:!1})||PEa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.sb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":$Ga(this,a);break;case "nowPlaying":bHa(this,a);break;case "onStateChange":aHa(this,a);break;case "onAdStateChange":cHa(this,a);break;case "onVolumeChanged":dHa(this,a);break;case "onSubtitlesTrackChanged":ZGa(this,a);break;case "nowAutoplaying":eHa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.R("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.R("autoplayModeChange",this.B);"DISABLED"==this.B&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":fHa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.iO=function(){if(this.A){var a=this.A;this.A=null;this.jb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.qG=function(){var a=3;this.ha()||(a=0,isNaN(this.Vm())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Ok=function(a){i8("Disconnecting with "+a);k8(this);this.R("beforeDisconnect",a);1==a&&r6();fGa(this.o,a);this.dispose()};
g.k.oG=function(){var a=this.jb;this.A&&(a=this.jb.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.uO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.A=b.videoId,g.fp(this.G),this.G=g.dp((0,g.x)(this.iO,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.playerState==b.playerState&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&X7(this.jb)==X7(b)&&g.fl(this.jb.o)==g.fl(b.o)||c.push("remotePlayerChange");this.jb.reset(a);g.z(c,function(d){this.R(d)},this)};
g.k.rz=function(){var a=this.o.F.id,b=g.jb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Vm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.dG=function(){return this.B||"UNSUPPORTED"};
g.k.eG=function(){return this.F||""};
g.k.iP=function(){if(!isNaN(this.Vm())){var a=this.o.u;g.Wn(a.o);a.start()}};
g.k.qO=function(a,b){n8(this,a,b);XGa(this)};
g.k.mE=function(){var a=g.Xq("SID","")||"",b=g.Xq("SAPISID","")||"";if(!a&&!b)return"";a=g.Jg(g.og(a),2);b=g.Jg(g.og(b),2);return g.Jg(g.og(a+","+b),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Ji;h8.prototype.getProxyState=h8.prototype.qG;h8.prototype.disconnect=h8.prototype.Ok;h8.prototype.getPlayerContextData=h8.prototype.oG;h8.prototype.setPlayerContextData=h8.prototype.uO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.rz;h8.prototype.getReconnectTimeout=h8.prototype.Vm;h8.prototype.getAutoplayMode=h8.prototype.dG;h8.prototype.getAutoplayVideoId=h8.prototype.eG;h8.prototype.reconnect=h8.prototype.iP;
h8.prototype.sendMessage=h8.prototype.qO;h8.prototype.getXsrfToken=h8.prototype.mE;g.t(o8,o7);g.k=o8.prototype;g.k.Le=function(a){return this.Id.$_gs(a)};
g.k.contains=function(a){return!!this.Id.$_c(a)};
g.k.get=function(a){return this.Id.$_g(a)};
g.k.start=function(){this.Id.$_st()};
g.k.add=function(a,b,c){this.Id.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Id.$_r(a,b,c)};
g.k.ks=function(a,b,c,d){this.Id.$_un(a,b,c,d)};
g.k.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.Id.$_ubk(this.o[a]);this.o.length=0;this.Id=null;o7.prototype.W.call(this)};
g.k.mP=function(){this.R("screenChange")};
g.k.VL=function(){this.R("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.nP;x7.prototype.$_gsppc=x7.prototype.qE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.ks;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Le;x7.prototype.$_gos=x7.prototype.pE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Ji;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.B);g.k=I8.prototype;g.k.W=function(){g.B.prototype.W.call(this);this.o.stop();this.u.stop();this.G.stop();this.M();var a=this.Ya;a.unsubscribe("proxyStateChange",this.lC,this);a.unsubscribe("remotePlayerChange",this.Rn,this);a.unsubscribe("remoteQueueChange",this.qr,this);a.unsubscribe("previousNextChange",this.hC,this);a.unsubscribe("nowAutoplaying",this.dC,this);a.unsubscribe("autoplayDismissed",this.DB,this);this.Ya=this.module=null};
g.k.PA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ya.o)if(J8(this)){if(!b8(this.Ya).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.Ya).sb()?this.Ya.pause():this.Ya.play();break;case "control_play":this.Ya.play();break;case "control_pause":this.Ya.pause();break;case "control_seek":this.F.zA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.CK=function(a){this.G.wG(a)};
g.k.RO=function(a){this.PA("control_subtitles_set_track",g.Tb(a)?null:a)};
g.k.BD=function(){var a=this.H.getOption("captions","track");g.Tb(a)||K8(this,a)};
g.k.Xb=function(a){this.module.Xb(a,this.H.getVideoData().lengthSeconds)};
g.k.TB=function(a){if(J8(this)){this.Ya.unsubscribe("remotePlayerChange",this.Rn,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.Ya);if(b!==c.volume||a!==c.muted)this.Ya.setVolume(b,a),this.I.start();this.Ya.subscribe("remotePlayerChange",this.Rn,this)}};
g.k.wL=function(){g.Tb(this.A)||rHa(this,this.A);this.B=!1};
g.k.lC=function(a,b){this.u.stop();2===b&&this.yD()};
g.k.Rn=function(){if(J8(this)){this.o.stop();var a=b8(this.Ya);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.kd=1;break;case 1082:case 1083:this.module.kd=0;break;default:this.module.kd=-1}switch(a.playerState){case 1081:case 1:this.Pc(new g.MI(8));this.xD();break;case 1085:case 3:this.Pc(new g.MI(9));break;case 1083:case 0:this.Pc(new g.MI(2));this.F.stop();this.Xb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Pc(new g.MI(4));break;case 2:this.Pc(new g.MI(4));
this.Xb(X7(a));break;case -1:this.Pc(new g.MI(64));break;case -1E3:this.Pc(new g.MI(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.Ya).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,rHa(this,a));a=b8(this.Ya);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.ZD()}else qHa(this)};
g.k.hC=function(){this.H.R("mdxpreviousnextchange")};
g.k.qr=function(){J8(this)||qHa(this)};
g.k.dC=function(a){isNaN(a)||this.H.R("mdxnowautoplaying",a)};
g.k.DB=function(){this.H.R("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.Ya.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.Ya).playerState?L8(this,a):b&&this.Ya.seekTo(a)};
g.k.ZD=function(){if(J8(this)){var a=b8(this.Ya);this.events.qb(this.N);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.N=this.events.L(this.H,"onVolumeChange",this.TB)}};
g.k.xD=function(){this.o.stop();if(!this.Ya.ha()){var a=b8(this.Ya);a.sb()&&this.Pc(new g.MI(8));this.Xb(X7(a));this.o.start()}};
g.k.yD=function(){this.u.stop();this.o.stop();var a=this.Ya.B.getReconnectTimeout();2==this.Ya.o&&!isNaN(a)&&this.u.start()};
g.k.Pc=function(a){this.u.stop();var b=this.C;if(!g.RI(b,a)){var c=g.W(a,2);c!==g.W(this.C,2)&&g.LT(this.H.app,c);this.C=a;tHa(this.module,b,a)}};g.t(M8,g.U);M8.prototype.Nb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){g.dP("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(N8,g.U);N8.prototype.Nb=function(){this.o.show()};
N8.prototype.Sa=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(O8,g.U);O8.prototype.u=function(a){sHa(this,a.state)};g.t(P8,g.gS);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Si=g.Fb(a,this.o,this),g.hS(this,g.Oc(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Pb(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Vf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Si[a].name};
P8.prototype.td=function(a){g.gS.prototype.td.call(this,a);this.H.setOption("remote","currentReceiver",this.Si[a]);this.Ha.Sa()};g.t(Q8,g.dO);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.O(),b=g.az(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.P(a.experiments,"mdx_load_cast_api_bootstrap_script")};kHa(b,a);this.subscriptions.push(g.kp("yt-remote-before-disconnect",this.AK,this));this.subscriptions.push(g.kp("yt-remote-connection-change",this.AM,this));this.subscriptions.push(g.kp("yt-remote-receiver-availability-change",this.jC,this));this.subscriptions.push(g.kp("yt-remote-auto-connect",this.yM,this));this.subscriptions.push(g.kp("yt-remote-receiver-resumed",
this.xM,this));this.subscriptions.push(g.kp("mdx-privacy-popup-confirm",this.YN,this));this.subscriptions.push(g.kp("mdx-privacy-popup-cancel",this.XN,this));this.subscriptions.push(g.kp("mdx-manual-pairing-popup-ok",this.tH,this));this.jC()};
g.k.load=function(){this.player.cancelPlayback();g.dO.prototype.load.call(this);this.pg=new I8(this,this.player,this.Ya);var a=(a=pHa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Xb(a);tHa(this,this.Ub,this.Ub);g.RT(this.player.app,6)};
g.k.unload=function(){this.player.R("mdxautoplaycanceled");this.bi=this.Sf;g.Ve(this.pg,this.Ya);this.Ya=this.pg=null;g.dO.prototype.unload.call(this);g.RT(this.player.app,5);R8(this)};
g.k.W=function(){g.lp(this.subscriptions);g.dO.prototype.W.call(this)};
g.k.Kg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.pg.PA.apply(this.pg,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.kd};
g.k.sG=function(){return this.loaded?this.pg.suggestion:null};
g.k.xg=function(){return this.Ya?b8(this.Ya).xg:!1};
g.k.hasNext=function(){return this.Ya?b8(this.Ya).hasNext:!1};
g.k.Xb=function(a,b){this.lA=a||0;this.player.R("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.lA};
g.k.getProgressState=function(){var a=b8(this.Ya),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.jd():!a.isAdPlaying()&&this.player.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.N,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.Ya&&this.Ya.nextVideo()};
g.k.vr=function(){this.Ya&&this.Ya.vr()};
g.k.AK=function(a){1===a&&(this.Nv=this.Ya?b8(this.Ya):null)};
g.k.AM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.bi;this.loaded&&this.unload();this.Ya=a;this.Nv=null;b.key!==this.Sf.key&&(this.bi=b,this.load())}else g.Ue(this.Ya),this.Ya=null,this.loaded&&(this.unload(),(a=this.Nv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.jC=function(){this.Si=[this.Sf].concat(mHa());var a=A8()||this.Sf;S8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.yM=function(){var a=A8();S8(this,a)};
g.k.xM=function(){this.bi=A8()};
g.k.YN=function(){this.Sn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.XN=function(){this.Sn=!1;R8(this);S8(this,this.Sf);this.bi=this.Sf;G8=!1;H8=null;this.player.playVideo()};
g.k.tH=function(){this.zq=!0;R8(this);g.zt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.fd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.bi:this.Sf;case "quickCast":return 2===this.Si.length&&"cast-selector-receiver"===this.Si[1].key?(b&&R7(),!0):!1}};
g.k.Hw=function(){this.Ya.Hw()};
g.k.fg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oO.remote=Q8;})(_yt_player);
