/*
 * Project name:
     MyProject.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     6/3/2021
 * Test configuration:
     MCU:             P18F87K22
     Dev.Board:       EasyPIC_PRO_v7_FT800
                      http://www.mikroe.com/easypic-pro/
     Oscillator:      64000000 Hz
     SW:              mikroC PRO for PIC
 */

#include "MyProject_objects.h"

void main() {

  InitVTFTStack();

  while (1) {
    ProcessVTFTStack();
  }

}